import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "./nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Jacob's Pet Shop",
  description: "Generated by create next app",
};

function getSeasonalTheme(): string {
  const month = new Date().getMonth(); 

  if (month >= 2 && month <= 4) {
    return "spring"; 
  } else if (month >= 5 && month <= 7) {
    return "summer"; 
  } else if (month >= 8 && month <= 10) {
    return "autumn";
  } else {
    return "winter"; 
  }
}

function getFontClass(season: string): string {
  switch (season) {
    case "spring":
      return "font-spring"; 
    case "summer":
      return "font-summer"; 
    case "autumn":
      return "font-autumn"; 
    case "winter":
      return "font-winter"; 
    default:
      return `${geistSans.variable} ${geistMono.variable}`;
  }
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const season = getSeasonalTheme();

  return (
    <html lang="en">
      <body className={`${getFontClass(season)} antialiased ${season}`}>
        <Nav season={season} /> 
        {children}
      </body>
    </html>
  );
}
